TITLE: Rafael Martins
TITLE_HTML: Rafael Martins
TAGLINE: Gentoo Linux, Engineering and random stuff.
AUTHOR: Rafael G. Martins
DISQUS: rafaelmartins-en
TIMEZONE: UTC
POSTS_PER_PAGE: 4
RST_HEADER_LEVEL: 4
EXTENSIONS:
    - machines
    - projects
    - resume
GITHUB_USERNAME: rafaelmartins
GITHUB_PROJECTS:
    - blohg
    - distpatch
    - balde
    - marrie
    - dnsimple-dyndns
    - cgisysinfo
    - ownpaste
    - github-repo-mirror
    - github-pages-publish
    - g-octave
