TITLE: Rafael Martins
TITLE_HTML: Rafael Martins
TAGLINE: Gentoo Linux, Engineering and random stuff.
AUTHOR: Rafael G. Martins
DISQUS: rafaelmartins-en
TIMEZONE: UTC
ENABLE_PLUGINS: True
PLUGINS:
    - projects
CACHE_DIR: /tmp/rafaelmartins.eng.br
