TITLE: Rafael Martins
TITLE_HTML: Rafael Martins
TAGLINE: Gentoo Linux, Engineering and random stuff.
AUTHOR: Rafael G. Martins
DISQUS: rafaelmartins-en
TIMEZONE: UTC
POSTS_PER_PAGE: 4
RST_HEADER_LEVEL: 4
EXTENSIONS:
    - draft
    - machines
    - projects
    - redirect
    - resume
REDIRECT:
    facebook: https://www.facebook.com/rafaelgmartins
    twitter: https://twitter.com/rafaelmartins
    medium: http://bit.ly/1gbznNo
    lattes: http://lattes.cnpq.br/7365999517312436
    pgp: http://pgp.mit.edu/pks/lookup?op=get&search=0x3EF74952E894ABDE
    github: https://github.com/rafaelmartins
    resume: http://rafaelmartins.eng.br/resume/resume-en.pdf
