TITLE: Rafael Martins
TITLE_HTML: Rafael Martins
TAGLINE: Gentoo Linux, Engineering and random stuff.
AUTHOR: Rafael G. Martins
DISQUS: rafaelmartins-en
TIMEZONE: UTC
POSTS_PER_PAGE: 4
RST_HEADER_LEVEL: 4
EXTENSIONS:
    - projects
    - resume
